/*
 * Samsung Exynos5 SoC series FIMC-IS driver
 *
 *
 * Copyright (c) 2011 Samsung Electronics Co., Ltd
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */

#ifndef IS_CMD_H
#define IS_CMD_H

#include "is-config.h"

#define IS_FRAME_DONE	0x1003

enum is_subscenario_id {
	ISS_SUB_SCENARIO_STILL_PREVIEW = 0,	/* 0: still preview */
	ISS_SUB_SCENARIO_VIDEO = 1,		/* 1: video */
	ISS_SUB_SCENARIO_UHD_30FPS_WDR_ON = 2,	/* 2: video UHD QHD 30fps (HDR ON) */
	ISS_SUB_SCENARIO_UHD_30FPS_WDR_AUTO = 3,/* 3: video UHD QHD 30fps (HDR AUTO) */
	ISS_SUB_SCENARIO_VIDEO_HIGH_SPEED = 4,	/* 4: video high speed */
	ISS_SUB_SCENARIO_STILL_CAPTURE = 5,	/* 5: still capture */
	ISS_SUB_SCENARIO_FHD_60FPS = 6,		/* 6: video FHD 60fps (HDR OFF)*/
	ISS_SUB_SCENARIO_UHD_30FPS = 7,		/* 7: video UHD QHD 30fps (HDR OFF) */
	ISS_SUB_SCENARIO_WVGA_300FPS = 8,	/* 8: video WVGA 300fps */
	ISS_SUB_SCENARIO_STILL_PREVIEW_WDR_ON = 9,
	ISS_SUB_SCENARIO_VIDEO_WDR_ON = 10,
	ISS_SUB_SCENARIO_STILL_CAPTURE_WDR_ON = 11,
	ISS_SUB_SCENARIO_STILL_CAPTURE_ZOOM = 13,
	ISS_SUB_SCENARIO_STILL_CAPTURE_ZOOM_INDOOR = 14,
	ISS_SUB_SCENARIO_STILL_CAPTURE_ZOOM_OUTDOOR = 15,
	ISS_SUB_SCENARIO_STILL_CAPTURE_WDR_ON_ZOOM = 16,
	ISS_SUB_SCENARIO_STILL_CAPTURE_DNG_REPROCESSING = 17,
	ISS_SUB_SCENARIO_FHD_60FPS_WDR_ON = 18,		/* 18: video FHD 60fps (HDR ON) */
	ISS_SUB_SCENARIO_STILL_CAPTURE_LLS = 19,
	ISS_SUB_SCENARIO_MERGED_STILL_CAPTURE_WDR_AUTO = ISS_SUB_SCENARIO_STILL_CAPTURE_LLS,
	ISS_SUB_SCENARIO_STILL_CAPTURE_WDR_ON_LLS = 20,
	ISS_SUB_SCENARIO_MERGED_STILL_CAPTURE_WDR_ON = ISS_SUB_SCENARIO_STILL_CAPTURE_WDR_ON_LLS,
	ISS_SUB_SCENARIO_UHD_60FPS_WDR_ON = 21,		/* 21: video UHD 60fps (HDR ON) */
	ISS_SUB_SCENARIO_UHD_60FPS = 22,		/* 22: video UHD 60fps (HDR OFF) */
	ISS_SUB_SCENARIO_UHD_60FPS_WDR_AUTO = 23,	/* 23: video UHD 60fps (HDR AUTO) */
	ISS_SUB_SCENARIO_STILL_CAPTURE_WDR_AUTO = 24,
	ISS_SUB_SCENARIO_VIDEO_WDR_AUTO = 25,
	ISS_SUB_SCENARIO_STILL_PREVIEW_WDR_AUTO = 26,
	ISS_SUB_SCENARIO_FHD_240FPS = 27,
	ISS_SUB_SCENARIO_MERGED_STILL_CAPTURE = 28,
	ISS_SUB_SCENARIO_FHD_60FPS_WDR_AUTO = 29,	/* 29: video FHD 60fps (HDR AUTO) */
	ISS_SUB_SCENARIO_STILL_CAPTURE_LONG = 30,
	ISS_SUB_SCENARIO_STILL_PREVIEW_BINNING = 40,	/* 40: binning mode for low power */
	ISS_SUB_SCENARIO_STILL_CAPTURE_BDS = 41,	/* 41: still capture bds */
	ISS_SUB_SCENARIO_STILL_PREVIEW_LLS = 42,	/* 42: still preview lls */
	ISS_SUB_SCENARIO_LIVE_OUTFOCUS_PREVIEW = 44,	/* 44 ~ 52: Bokeh (HDR off/auto/on) */
	ISS_SUB_SCENARIO_LIVE_OUTFOCUS_CAPTURE = 45,
	ISS_SUB_SCENARIO_LIVE_OUTFOCUS_PREVIEW_WDR_AUTO = 47,
	ISS_SUB_SCENARIO_LIVE_OUTFOCUS_PREVIEW_WDR_ON = 48,
	ISS_SUB_SCENARIO_LIVE_OUTFOCUS_CAPTURE_WDR_AUTO = 49,
	ISS_SUB_SCENARIO_LIVE_OUTFOCUS_CAPTURE_WDR_ON = 50,
	ISS_SUB_SCENARIO_STILL_PREVIEW_3RD_PARTY_WDR_AUTO = 51,
	ISS_SUB_SCENARIO_VIDEO_3RD_PARTY_WDR_AUTO = 52,
	ISS_SUB_SCENARIO_MERGED_STILL_CAPTURE_MFHDR = 53,
	ISS_SUB_SCENARIO_MERGED_STILL_CAPTURE_LLHDR = 54,
	ISS_SUB_SCENARIO_SUPER_NIGHT_SHOT = 55,
	ISS_SUB_SCENARIO_FHD_VIDEO_HDR10_WDR_ON = 56,
	ISS_SUB_SCENARIO_UHD_VIDEO_HDR10_WDR_ON = 57,
	ISS_SUB_SCENARIO_BINNING = 58,
	ISS_SUB_SCENARIO_VIDEO_ISPLP_TNR = 59,
	ISS_SUB_SCENARIO_STILL_NIGHT_HDR = 60,
	ISS_SUB_SCENARIO_VIDEO_SUPER_STEADY = 61,
	ISS_SUB_SCENARIO_STILL_FLASH_LLS = 62,

	ISS_SUB_SCENARIO_FRONT_VT1 = 31,			/* 31: front camera VT1 */
	ISS_SUB_SCENARIO_FRONT_VT2 = 32,			/* 32: front camera VT2 */
	ISS_SUB_SCENARIO_FRONT_SMART_STAY = 33,			/* 33: front camera smart stay */
	ISS_SUB_SCENARIO_FRONT_PANORAMA = 34,			/* 34: front camera front panorama */
	ISS_SUB_SCENARIO_FRONT_C2_OFF_STILL_PREVIEW = 35,	/* 35: C2 off front still preview */
	ISS_SUB_SCENARIO_FRONT_C2_OFF_STILL_CAPTURE = 36,	/* 36: C2 off front still capture */
	ISS_SUB_SCENARIO_FRONT_C2_OFF_VIDEO = 37,		/* 37: C2 off front video */
	ISS_SUB_SCENARIO_FRONT_VT4 = 38,			/* 38: front camera VT4 */
	ISS_SUB_SCENARIO_FRONT_VT1_STILL_CAPTURE = 39,		/* 39: front camera VT1 still capture */
	ISS_SUB_SCENARIO_FRONT_STILL_PREVIEW_BINNING = 40,	/* 40: front camera binning mode for low power */
	ISS_SUB_SCENARIO_FRONT_COLOR_IRIS_PREVIEW = 43,		/* 43: front camera Color Iris preview */
	ISS_SUB_END,
};

#define IS_VIDEO_SCENARIO(setfile)				\
	(((setfile) == ISS_SUB_SCENARIO_VIDEO)			\
	|| ((setfile) == ISS_SUB_SCENARIO_VIDEO_WDR_AUTO)	\
	|| ((setfile) == ISS_SUB_SCENARIO_VIDEO_WDR_ON)		\
	|| ((setfile) == ISS_SUB_SCENARIO_FHD_60FPS)		\
	|| ((setfile) == ISS_SUB_SCENARIO_FHD_60FPS_WDR_AUTO)	\
	|| ((setfile) == ISS_SUB_SCENARIO_UHD_30FPS)		\
	|| ((setfile) == ISS_SUB_SCENARIO_UHD_30FPS_WDR_AUTO)	\
	|| ((setfile) == ISS_SUB_SCENARIO_UHD_30FPS_WDR_ON)	\
	|| ((setfile) == ISS_SUB_SCENARIO_UHD_60FPS)		\
	|| ((setfile) == ISS_SUB_SCENARIO_UHD_60FPS_WDR_AUTO)	\
	|| ((setfile) == ISS_SUB_SCENARIO_WVGA_300FPS)		\
	|| ((setfile) == ISS_SUB_SCENARIO_FRONT_C2_OFF_VIDEO)	\
	|| ((setfile) == ISS_SUB_SCENARIO_FHD_240FPS))

#define IS_VIDEO_HDR_SCENARIO(setfile)				\
	(((setfile) == ISS_SUB_SCENARIO_VIDEO_WDR_AUTO)		\
	|| ((setfile) == ISS_SUB_SCENARIO_VIDEO_WDR_ON))

enum is_scenario_is {
	IS_SCENARIO_SWVDIS = 1,
	IS_SCENARIO_COLOR_IRIS = 2,
	IS_SCENARIO_AUTO_DUAL = 3,
	IS_SCENARIO_FULL_SIZE = 4,
	IS_SCENARIO_HIGH_SPEED_DUALFPS = 5, /* FPS is changed from normal to high speed */
	IS_SCENARIO_SECURE = 6,
	IS_SCENAIRO_REMOSAIC = 7,
};

enum is_msg_test_id {
	IS_MSG_TEST_SYNC_LOG = 1,
};

#ifdef CONFIG_USE_SENSOR_GROUP
#define MAX_ACTIVE_GROUP 8
#else
#define MAX_ACTIVE_GROUP 6
#endif
struct is_path_info {
	u32 sensor_name;
	u32 mipi_csi;
	u32 reserved;
	/*
	 * uActiveGroup[0] = GROUP_ID_0/GROUP_ID_1/0XFFFFFFFF
	 * uActiveGroup[1] = GROUP_ID_2/GROUP_ID_3/0XFFFFFFFF
	 * uActiveGroup[2] = GROUP_ID_4/0XFFFFFFFF
	 * uActiveGroup[3] = GROUP_ID_5(MCSC0)/GROUP_ID_6(MCSC1)/0XFFFFFFFF
	 * uActiveGroup[4] = GROUP_ID_7/0XFFFFFFFF
	 */
	u32 group[MAX_ACTIVE_GROUP];
};

#endif
