#
# Makefile for ccic devices
#

obj-$(CONFIG_CCIC_S2MU107)  += s2mu107-usbpd.o
obj-$(CONFIG_CCIC_S2MU106)  += s2mu106-usbpd.o
obj-$(CONFIG_USE_CCIC)      += usbpd.o usbpd_cc.o
obj-$(CONFIG_USE_CCIC)      += usbpd_policy.o usbpd_manager.o
obj-$(CONFIG_CCIC_SYSFS)        += usbpd_sysfs.o
